// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: ''),
    appId: '1:118165710666:web:2b98ad12c71d69467143b3',
    messagingSenderId: '118165710666',
    projectId: 'synthese-c2958',
    authDomain: 'synthese-c2958.firebaseapp.com',
    storageBucket: 'synthese-c2958.firebasestorage.app',
    measurementId: 'G-66JF9N7C34',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:118165710666:android:f9e77be691d911db7143b3',
    messagingSenderId: '118165710666',
    projectId: 'synthese-c2958',
    storageBucket: 'synthese-c2958.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: ''),
    appId: '1:118165710666:ios:2e1b89b25926f09b7143b3',
    messagingSenderId: '118165710666',
    projectId: 'synthese-c2958',
    storageBucket: 'synthese-c2958.firebasestorage.app',
    iosBundleId: 'com.example.synthese',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: ''),
    appId: '1:118165710666:ios:2e1b89b25926f09b7143b3',
    messagingSenderId: '118165710666',
    projectId: 'synthese-c2958',
    storageBucket: 'synthese-c2958.firebasestorage.app',
    iosBundleId: 'com.example.synthese',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: '1:118165710666:web:9721809990eb81bc7143b3',
    messagingSenderId: '118165710666',
    projectId: 'synthese-c2958',
    authDomain: 'synthese-c2958.firebaseapp.com',
    storageBucket: 'synthese-c2958.firebasestorage.app',
    measurementId: 'G-T92B1887WM',
  );
}
